scp ./startdb.sh pi@AB01:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB02:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB03:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB04:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB05:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB06:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB07:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB08:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB09:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB10:/home/pi/ab72/bin/startdb.sh
scp ./startdb.sh pi@AB11:/home/pi/ab72/bin/startdb.sh
