select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
set timing on;

-- $ID$
-- TPC-H/TPC-R CUSTOMER DISTRIBUTION QUERY (Q13)
-- FUNCTIONAL QUERY DEFINITION
-- APPROVED FEBRUARY 1998
:X
:O
SELECT
	C_COUNT,
	COUNT(*) AS CUSTDIST
FROM
	(
		SELECT
			C_CUSTKEY,
			COUNT(O_ORDERKEY) AS C_COUNT
		FROM
			CUSTOMER LEFT OUTER JOIN ORDERS ON
				C_CUSTKEY = O_CUSTKEY
				AND O_COMMENT NOT LIKE '%:1%:2%'
		GROUP BY
			C_CUSTKEY
	) C_ORDERS 
GROUP BY
	C_COUNT
ORDER BY
	CUSTDIST DESC,
	C_COUNT DESC;

set timing off;
select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
