select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
set timing on;

-- $ID$
-- TPC-H/TPC-R TOP SUPPLIER QUERY (Q15)
-- FUNCTIONAL QUERY DEFINITION
-- APPROVED FEBRUARY 1998
:X
CREATE VIEW REVENUE:S (SUPPLIER_NO, TOTAL_REVENUE) AS
	SELECT
		L_SUPPKEY,
		SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
	FROM
		LINEITEM
	WHERE
		L_SHIPDATE >= DATE':1'
		AND L_SHIPDATE < ADD_MONTHS(DATE':1', 3)
	GROUP BY
		L_SUPPKEY;

:O
SELECT
	S_SUPPKEY,
	S_NAME,
	S_ADDRESS,
	S_PHONE,
	TOTAL_REVENUE
FROM
	SUPPLIER,
	REVENUE:S
WHERE
	S_SUPPKEY = SUPPLIER_NO
	AND TOTAL_REVENUE = (
		SELECT
			MAX(TOTAL_REVENUE)
		FROM
			REVENUE:S
	)
ORDER BY
	S_SUPPKEY;

DROP VIEW REVENUE:S;

set timing off;
select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
