select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
set timing on;

-- $ID$
-- TPC-H/TPC-R ORDER PRIORITY CHECKING QUERY (Q4)
-- FUNCTIONAL QUERY DEFINITION
-- APPROVED FEBRUARY 1998
:X
:O
SELECT
	O_ORDERPRIORITY,
	COUNT(*) AS ORDER_COUNT
FROM
	ORDERS
WHERE
	O_ORDERDATE >= DATE':1'
	--AND O_ORDERDATE < DATE':1' + INTERVAL '3' MONTH
	AND O_ORDERDATE < ADD_MONTHS(':1', 3)
	AND EXISTS (
		SELECT
			*
		FROM
			LINEITEM
		WHERE
			L_ORDERKEY = O_ORDERKEY
			AND L_COMMITDATE < L_RECEIPTDATE
	)
GROUP BY
	O_ORDERPRIORITY
ORDER BY
	O_ORDERPRIORITY;

set timing off;
select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
