select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
set timing on;

-- $ID$
-- TPC-H/TPC-R FORECASTING REVENUE CHANGE QUERY (Q6)
-- FUNCTIONAL QUERY DEFINITION
-- APPROVED FEBRUARY 1998
:X
:O
SELECT
	SUM(L_EXTENDEDPRICE * L_DISCOUNT) AS REVENUE
FROM
	LINEITEM
WHERE
	L_SHIPDATE >= DATE':1'
	--AND L_SHIPDATE < DATE ':1' + INTERVAL '1' YEAR
	AND L_SHIPDATE < ADD_MONTHS(':1', 12)
	AND L_DISCOUNT BETWEEN :2 - 0.01 AND :2 + 0.01
	AND L_QUANTITY < :3;

set timing off;
select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
