select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
set timing on;

-- $ID$
-- TPC-H/TPC-R VOLUME SHIPPING QUERY (Q7)
-- FUNCTIONAL QUERY DEFINITION
-- APPROVED FEBRUARY 1998
:X
:O
SELECT
	SUPP_NATION,
	CUST_NATION,
	L_YEAR,
	SUM(VOLUME) AS REVENUE
FROM
	(
		SELECT
			N1.N_NAME AS SUPP_NATION,
			N2.N_NAME AS CUST_NATION,
			--EXTRACT(YEAR FROM L_SHIPDATE) AS L_YEAR,
			EXTRACT(L_SHIPDATE, 'YEAR') AS L_YEAR,
			L_EXTENDEDPRICE * (1 - L_DISCOUNT) AS VOLUME
		FROM
			SUPPLIER,
			LINEITEM,
			ORDERS,
			CUSTOMER,
			NATION N1,
			NATION N2
		WHERE
			S_SUPPKEY = L_SUPPKEY
			AND O_ORDERKEY = L_ORDERKEY
			AND C_CUSTKEY = O_CUSTKEY
			AND S_NATIONKEY = N1.N_NATIONKEY
			AND C_NATIONKEY = N2.N_NATIONKEY
			AND (
				(N1.N_NAME = ':1' AND N2.N_NAME = ':2')
				OR (N1.N_NAME = ':2' AND N2.N_NAME = ':1')
			)
			AND L_SHIPDATE BETWEEN DATE'1995-01-01' AND DATE'1996-12-31'
	) AS SHIPPING
GROUP BY
	SUPP_NATION,
	CUST_NATION,
	L_YEAR
ORDER BY
	SUPP_NATION,
	CUST_NATION,
	L_YEAR;

set timing off;
select to_char(systimestamp, 'YYYY-MM-DD HH-MI-SS.FF3')  from dual;
