CREATE VIEW REVENUE ( SUPPLIER_NO, TOTAL_REVENUE )
    AS SELECT L_SUPPKEY,
              SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))
       FROM LINEITEM
       WHERE L_SHIPDATE >= DATE'1996-01-01'
         AND L_SHIPDATE < ADD_MONTHS(DATE'1996-01-01', 3)
       GROUP BY L_SUPPKEY;


SELECT S_SUPPKEY,
       S_NAME,
       S_ADDRESS,
       S_PHONE,
       TOTAL_REVENUE
FROM SUPPLIER,
     REVENUE
WHERE S_SUPPKEY = SUPPLIER_NO
  AND TOTAL_REVENUE = ( SELECT MAX(TOTAL_REVENUE) FROM REVENUE )
ORDER BY S_SUPPKEY; 
