isql -u sys -p manager -s pc1 -f 1.crtuser.sql
isql -u sys -p manager -s pc2 -f 1.crtuser.sql
isql -u sys -p manager -s pc3 -f 1.crtuser.sql
isql -u sys -p manager -s pc4 -f 1.crtuser.sql
isql -u sys -p manager -s pc5 -f 1.crtuser.sql
isql -u sys -p manager -s pc6 -f 1.crtuser.sql
isql -u sys -p manager -s pc7 -f 1.crtuser.sql
isql -u sys -p manager -s pc8 -f 1.crtuser.sql
isql -u sys -p manager -s pc9 -f 1.crtuser.sql
isql -u sys -p manager -s pc0 -f 1.crtuser.sql
