all:  bmt_insert_context.class bmt_insert.class bmt_select_context.class bmt_select.class bmt_update_context.class bmt_update.class bmt_delete_context.class bmt_delete.class


bmt_insert_context.class: bmt_insert_context.java
	javac bmt_insert_context.java

bmt_insert.class: bmt_insert.java
	javac bmt_insert.java


bmt_select_context.class: bmt_select_context.java
	javac bmt_select_context.java

bmt_select.class: bmt_select.java
	javac bmt_select.java


bmt_update_context.class: bmt_update_context.java
	javac bmt_update_context.java

bmt_update.class: bmt_update.java
	javac bmt_update.java


bmt_delete_context.class: bmt_delete_context.java
	javac bmt_delete_context.java

bmt_delete.class: bmt_delete.java
	javac bmt_delete.java


clean:
	-rm -f bmt_insert_context.class bmt_insert.class
	-rm -f bmt_select_context.class bmt_select.class
	-rm -f bmt_update_context.class bmt_update.class
	-rm -f bmt_delete_context.class bmt_delete.class
