DROP TABLE TEST;

CREATE TABLE TEST (
    K01  BIGINT NOT NULL,
    K02  VARCHAR(64),
    K03  INTEGER,
    K04  INTEGER,
    K05  DATE,
    K06  INTEGER
);

ALTER TABLE TEST ADD CONSTRAINT TEST_INDEX PRIMARY KEY ( K01 );
