/***********************************************************************
 * Copyright 1999-2015, ALTIBASE Corporation or its subsidiaries.
 * All rights reserved.
 **********************************************************************/

create or replace package body utl_tcp WRAPPED
'MTQ1MA==
NjA0
AD5jcmVhdGUgb3IgcmVwbGFjZSBwYWNrYWdlIGJvZHkgdXRsX3RjcCBpcwoKRlVOQ1RJT04gb3Blbl9jb25uZWN0aW9uKHJlbW90ZV9ob3N0IGAADUlOIFZBUkNIQVIoNjQpLApsAjMMAMMHcG9yJ+AABElOVEVHRVI50AACbG9jYWwosQEgLLQBfAwJREVGQVVMVCBOVUxMPyABJ/ABYAnVDyAgBgQBDGluX2J1ZmZlcl9zaXplICASBwFvdXQrCgFJTlAIhCAgBwwCA2NoYXJzZbwncB8pOwQxNilkAiAGMAMEbmV3bGluZWQGjAApIQEyKxwBAUNSTEY5WAUGdHhfdGltZW91zBIgEUgDCHdhbGxldF9wYXRoLyUCNSAMTAMnJAEDc3N3b3JkTCvkU2ALKmEEKTiUCgAEUkVUVVJOIENPTk5FQ1RfVFlQRQphc58FcmV0K1wABDsKYmVnaW4nbAAFOj0gT1BFTl/OByggxF5pZSzwAWVQLLFVIC4+CCk77wl1cm5IdAR0OwplbmQ7KTMOd3JpTG8CcmF3KGNsGlQt0A2AFQQgLApkYXRhYB90A8wABVJBVyg2NTUzc3NsZW6AV8gDeAAyFgwpCtgg0ANkICusA3wTJywCAyAoIGMsIGYPLCBhDCkv2gJpc+SISAV4EyrWAikgIAKwASgGAWVkbAgnjAEMUFJPQ0VEVVJFIGNsb3Nl/AxllWMvpAF8GGweCmR1bW15IGludGVnZXIqGAegA0A5KzIBKGM3uAFQVynJAXMgDoABKfUAKCeIAQJlbmQ7ChEAADk5OTU5RDg5NzlBNEE2NzJEQThBNUZCRTJGNjYxN0Y2REQyMTI2NTE=
';
/


