apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: yu3papa/k8s_guestbook:ingress
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: guestbook