. /home/jhpark/SHARD/DN1/conf/altibase_user.env
server start
. /home/jhpark/SHARD/DN2/conf/altibase_user.env
server start
. /home/jhpark/SHARD/DN3/conf/altibase_user.env
server start
. /home/jhpark/SHARD/DN4/conf/altibase_user.env
server start
. /home/jhpark/SHARD/DN5/conf/altibase_user.env
server start
