isql -u SMSSUSER -p SMSSUSER -s AB01 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB02 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB03 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB04 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB05 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB06 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB07 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB08 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB09 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB10 -f 2.schema.sql
isql -u SMSSUSER -p SMSSUSER -s AB11 -f 2.schema.sql
