isql -u sys -p manager -s AB01 < 4.crt_src_rep1.sql
isql -u sys -p manager -s AB02 < 4.crt_src_rep2.sql
isql -u sys -p manager -s AB03 < 4.crt_src_rep3.sql
isql -u sys -p manager -s AB04 < 4.crt_src_rep4.sql
isql -u sys -p manager -s AB05 < 4.crt_src_rep5.sql
isql -u sys -p manager -s AB06 < 4.crt_src_rep6.sql
isql -u sys -p manager -s AB07 < 4.crt_src_rep7.sql
isql -u sys -p manager -s AB08 < 4.crt_src_rep8.sql
isql -u sys -p manager -s AB09 < 4.crt_src_rep9.sql
isql -u sys -p manager -s AB10 < 4.crt_src_rep10.sql
