isql -u sys -p manager -s AB01 < 6.start_src_rep1.sql 
isql -u sys -p manager -s AB02 < 6.start_src_rep2.sql 
isql -u sys -p manager -s AB03 < 6.start_src_rep3.sql 
isql -u sys -p manager -s AB04 < 6.start_src_rep4.sql 
isql -u sys -p manager -s AB05 < 6.start_src_rep5.sql 
isql -u sys -p manager -s AB06 < 6.start_src_rep6.sql 
isql -u sys -p manager -s AB07 < 6.start_src_rep7.sql 
isql -u sys -p manager -s AB08 < 6.start_src_rep8.sql 
isql -u sys -p manager -s AB09 < 6.start_src_rep9.sql 
isql -u sys -p manager -s AB10 < 6.start_src_rep10.sql 
