/***********************************************************************
 * Copyright 1999-2015, ALTIBASE Corporation or its subsidiaries.
 * All rights reserved.
 **********************************************************************/

CREATE PACKAGE BODY DBMS_RECYCLEBIN WRAPPED
'MzA3MQ==
ODgx
AB5DUkVBVEUgUEFDS0FHRSBCT0RZIERCTVNfUkVDWUNMRUJJTiBBUwoKUFJPQ0VEVVJIBQZVUkdFX1VTRVItjAAAH1RZUEUgTkFNRV9BUlJBWSBJUyBUQUJMRSBPRiBWQVJDSEFSKDEyOCkgSU5ERVggQllAAQlURUdFUjsKClNRTCBAAPgEBDI1Nik7Ck5GAiAgKJQAlQlTKYgBDTsKQkVHSU4KICBTRUxFQ1S9DV9sEAYgQlVMSyBDT0ycAgFJTlRPsgNTCnAKDkZST00gU1lTVEVNXy5TWVNfqAsBXyBULCdbAERCQZQcAVNfIFWQBgVXSEVSRSBVLogfAklEID0gxAEDKCkgQU5EK2UAVCeUAGYDVC6dC1+EJAs9J1InOwoKICBGT1IgTlQbwBMILkZJUlNUKCkgLi7mAkxBgAIBTE9PUFwFYBd8JAI6PSAnUHAwuAQDICInIHx8rBFkH0QIWwEnIi68AoQPAVMoTimQAkQPegggIOAntAENIEVYRUNVVEUgSU1NRURJQUQBAVNRTDvQDgdFWENFUFRJT04gSCABTiBPVEIhUyBUAGQvwwhOVUwovgBORGgHAUVORCBrFzsKRWACLwsJQUxMIGIECW44UyAgBVEJLCiUBTd8CawEICyYCSBVMAlsRmBLIIIkCaxcTphFKK1iU2wBvoBJTifwEQI2NCkgKXSZnHBsZSAZpBLYXlgAM8wSXALIAEiPrJwokAKBE18qWgI7CrQDzAZ4ACh6AjsKzFR4AqwAKnAA5HkFSUYgSU5TVFIvCAQELCBDSFIoM5MfPSAwKuAOtA4nsgRfIEyLAVVQUEUwEQEgXLEDICBFTFNF0IIy6AAFUkVQTEFDRTI6CALmg0lGkKAv4Ba8Z4gkID+MDQJULlRCU6UNPS7dCF9ousgdbC4q2BcrPA4pjAAgR5gXIIpkDgVPUklHSU5BTJYsKCArOABo3/BnI1wgIC9sDvALKzQhcDlsACdcDitMAihUDmQSL1gOPNwNKyQBOdQNK5wAKswNK2AAL8QNK3QAmAYovA0rbAAp6AE+tA03iA2YWiAzmCSAC2EwIDjAJCmMACtgAwRfID0gU1VCUpxCKPBtaDIILCAxLCBMRU5HVEgsYAAEKSAtIDMyKS0sD+gHmsA9ICM8JiDROCYCRU5EOwoRAAA3OTM3NERCRjM3Njc3NTJFMTA1OEMwNTEzOUEyM0U4OUJFRTRCREU2
';
/

