/***********************************************************************
 * Copyright 1999-2015, ALTIBASE Corporation or its subsidiaries.
 * All rights reserved.
 **********************************************************************/

create or replace package body dbms_sql WRAPPED
'ODcwMg==
MTE3NA==
ADBjcmVhdGUgb3IgcmVwbGFjZSBwYWNrYWdlIGJvZHkgZGJtc19zcWwKYXMKCmZ1bmN0aW9uIG9wZW5fY3Vyc29yKClABwl0dXJuIGludGVnZXJlBWPwAQ07CmJlZ2luCmMgOj0gc3BfK+AAATsKcmWEBwNjOwplbmQqVQE7KbIBaXOZBihwCvwKJ9ABBGJvb2xlYW5yDmEg0AHxDmHQDicBASknxQFhpA7EA1QNBXByb2NlZHVyeB8DcnNlKGMgKgEAaSd2AywKKlwAbAFQI3gAzAAPaW4gdmFyY2hhcjIoMzIwMDApMMQACmxhbmd1YWdlX2ZsYWdEGkgAhScptBjcKC4WA3BhnBIDLCBzcWwpuBeIAivwAgJiaW5kX0AQAWlhYmzwGDrwAtQWAyBuYW1lIFwQKPMCMTI4MegC/AUCdmFsdWUrvACwHTwIAyt0AngUfyQoYyyZDyxPD2x1ZcgbK6gAIF2IA5AUIBF4A5gGIH9sA8xNIAvYBsgGIIDaBmJpQY90IAtkA6QGIIBgAwJzbWFsbFQwIAtoA+wGIIBwAwNkb3VibGUgC2gDpAYggGADAXJlYWwgC1gDfAUggFADCG51bWVyaWMoMzgpIAtsA/gGIH93FGRhdCANKgphdFDuIAM4GyckJQRleGVjdXRlJjAlNIwjhJkkcCCslC5sIC4UAS+gIyyAACs8HQJkZWZpbkAQAm9sdW1uLNwjIAPkIAFwb3NpI0woImggIAPBAGOADVT/OQQhJNAoAW51bGwkoCMrjAIgbPQClPwpcCAgieQCRMgiuC6cdiCJ1AK8XyCO0AL07yCO2AKk6yCO0AJ85iCOyAL44fToIIk0DieAHCAWyQJfmKcrrD0gAwgZac0gIBDgGZQGLvQZgBC8tzCgPoQG8ADHB3NpeiSkPCAI/BSQHFDWJ8wfB2ZldGNoX3Jvd3MjTEMk7D8xFkVhIMwMLrgfKgABL6gfKHAATA4oWEPYFyPgPiyUHyIYP8ANNwgEK7AFIAPAACq4AQQgIG91dCB2LFhEjHQphAPABgJlcnJvckAMkCIMOwphY3R1YWxfbGVuZ3RoKFgAuE0mfEfIB4kbX9oMKGM3LAOgOuQaPZgAKmwBIAWoAIQYPagAK1gDJcRDKqQBIG3kBimMDCA31AaIDDvIBiADvAYqCAU6BAbcBD+kBiCNmAbMeCA3iAbYCyAALGANKTArIDIkFLQLPrwGIANeDSAgxGaIrDpkDSekAD9uDSAgII10DSsMLyAytAb8Cz69BiAn4CM8HAYnJAYgAswGJ6wAIALUBiCP3AYpEDMgMtQGtAs+zAYgAAiMDSfsNiAypAZsCzycBiADlAYgBxwU3AQ/PA0gjQwULqA6IDKYBugMOy0oICAIEBTcMCADDBTIBT/JBiAgkAQUMRRbKrADKFg1KzQKKFgAObQ1IgBAIJ9UDQFsb3NlK/xdIrQ6JbQrLjAtLSgEK+oAKTskmIMBTlVMTCTZWmMpfQA7KUSDAmxhc3RfgU1f8I4gDRiFMwABJ3CDJTiFMZIAOwojoIUHZGJtc19zcWw7ChEAADk1NjkwNTI2NUZENTY0MTA1NzkwMTdGOTlEQ0VDNkQ0NzY2OEU4Nzc=
';
/

