/***********************************************************************
 * Copyright 1999-2015, ALTIBASE Corporation or its subsidiaries.
 * All rights reserved.
 **********************************************************************/

CREATE OR REPLACE FUNCTION SYS_CONTEXT WRAPPED
'MjM3OA==
ODc2
ABxDUkVBVEUgT1IgUkVQTEFDRSBGVU5DVElPTiBTWVNfQ09OVEVYVCggTkFNRVNQfAMOSU4gVkFSQ0hBUigzMCksCiAgBgAAB1BBUkFNRVRFUiAsBAEFICkKUkVUVVIoWAEACTI1NikgQVVUSElEIENVUlJFTlRfVVNFUgpBU5QNWAUBX1ZBTCfcAfgRfQY7hwRVUF8owAJcBOcEMzApJ4AAKDwCMoAAAwpCRUdJTjAwAQY6PSBVUFBFUignfAHECosFSUYgK+sBPSAnYBcFRU5WJyBUSEW8CVgNkAVcAHQFKBwCJ2wBJ0gATAsnqACsCydpACBPC0NMSWwjAUlORk8sfAFoCwUgU0VMRUNUICmQAEYvVE9BPVSYJwhGUk9NIFYkU0VTU3g9A3doZXJlIEouPSDIAgFfSUQoKgQCAUVMU0UxFAIESVBfQUREUlgIMRACAApzZWxlY3Qgc3Vic3RyKGNvbW1fbmFtZSw1LGluLEQACSc6JyktNSkgaW50byeMAgxmcm9tIHYkc2Vzc2lvbiCuFGlkUB/LAl9pZGwUgx4gICA2iAIBU0RCQTh0AgZERUNPREUoU1l4BAACX0ZMQUcsMSwnVFJVRScsMCwnRkFBHycgNWQCBUxBTkdVQUdFOHACAAZubHNfdGVycml0b3J5fHwnLid8fE5MU19kcAVBQ1RFUlNFVDrQBAEsIHYkbwhwYXJALwF0ZXJz2CgoBwUgPSBMKgFhbmQgK0wAKDAAaCwnIAo1jAWMEpZ1Q1k8NAMFY3VycmVuY3k61ALMFFkSPSlQAiAHHAIIREFURV9GT1JNQVQ4KAIFREVGQVVMVF8psAAgOUQCXJ4CUklUT1I5aARgKCeYACA1JAJfRUlPTjFIBMyFvAM7mBACV0hFUkUgE5gQ5LkCU0NIRU0yMA74unugU0VShLggA8IHREKIBThUA8AEM1gDUD8EQUJBU0U7Cj5/C0hPUzIwCSnUAmQEiBEgA9QCBElOU1RBTkMy4A8pSwEnMScgAWQCAk1PRFVMMiAB1Dq8AzP4A8W9ICAYVAfACJzzMQQGKSgDYOEgCHcEU0lEPDQB/A4xiBonIAdwwikAAgFOVUxMtP9gAwNFTkQgSUa8AWSaJ9QAL8QAhAP4BZABSwRVUk7w1AQ7CkVORDsKEQAARTFENTM5QURENTJDOEFBNjIxQTREMEQxMTM0QzgyMDdEOUQ0MkNFMA==
';
/

create or replace public synonym sys_context for sys.sys_context;
grant execute on sys.sys_context to public;

