isql -u sys -p manager -s pc1 < 6.start_src_rep1.sql 
isql -u sys -p manager -s pc2 < 6.start_src_rep2.sql 
isql -u sys -p manager -s pc3 < 6.start_src_rep3.sql 
isql -u sys -p manager -s pc4 < 6.start_src_rep4.sql 
isql -u sys -p manager -s pc5 < 6.start_src_rep5.sql 
isql -u sys -p manager -s pc6 < 6.start_src_rep6.sql 
isql -u sys -p manager -s pc7 < 6.start_src_rep7.sql 
isql -u sys -p manager -s pc8 < 6.start_src_rep8.sql 
isql -u sys -p manager -s pc9 < 6.start_src_rep9.sql 
